name: Actualizador Automatico de Noticias IA
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  actualizar-noticias:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Ejecutar script de actualización
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python script.py

      - name: Guardar cambios en la Web
        run: |
          git config --global user.name "Robot Noticiero IA"
          git config --global user.email "bot@ia.com"
          git add índice.html
          git commit -m "Noticia automatica añadida" || echo "No hay cambios"
          git push
